name: coffee_repository
description: Dart repository for managing coffee data.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  alex_flipnote_coffee_api:
    path: ../alex_flipnote_coffee_api
  equatable: ^2.0.5
  json_annotation: ^4.6.0
  local_storage_api:
    path: ../local_storage_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
