name: coffee_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  alex_flipnote_coffee_api:
    path: ../alex_flipnote_coffee_api
  equatable: ^2.0.5
  json_annotation: ^4.6.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
